import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

export async function sendSummaryEmail({
  to,
  title,
  summary,
}: {
  to: string;
  title: string;
  summary: any;
}) {
  if (!to) return;

  const html = `
    <div style="font-family: Arial, sans-serif; padding: 20px;">
      <h2 style="margin-bottom: 10px;">Decision Layer Summary</h2>
      <h3 style="margin-bottom: 20px;">${title}</h3>

      <p><strong>Top Signal:</strong> ${summary?.topSignal || '-'}</p>
      <p><strong>Recommendation:</strong> ${summary?.recommendation || '-'}</p>
      <p><strong>Decision:</strong> ${summary?.decision || '-'}</p>
      <p><strong>Tradeoff:</strong> ${summary?.tradeoff || '-'}</p>

      <hr style="margin: 20px 0;" />

      <p>${summary?.overallSummary || ''}</p>

      <hr style="margin: 20px 0;" />

      <p style="font-size: 12px; color: #666;">
        Generated by Decision Layer
      </p>
    </div>
  `;

  await resend.emails.send({
    from: 'Decision Layer <onboarding@resend.dev>',
    to,
    subject: `Summary: ${title}`,
    html,
  });
}